--- 
clone: 
  depth: 1
kind: pipeline
name: EvaPipeline
steps: 
  - name: Kernel Pipeline
    image: archlinux:base-devel
    commands: 
      - pacman -Syu --needed --noconfirm wget base-devel xmlto inetutils bc cpio python-sphinx python-sphinx_rtd_theme graphviz imagemagick git python2 python zip
      - export LANG=C && export LC_ALL=en_US.UTF-8
      - make O=out cherry_defconfig
      - make O=out -j$(nproc --all)
  - name: Publish
    image: plugins/github-release
    settings:
      api_key:
         from_secret: github_token
      files: out/arch/x86_64/boot/bzImage 
      title: Beta1
    when: 
      event: tag
